import type { Metadata } from "next";
import "./globals.css";
import { avenirNext } from "@/styles/fonts/fonts";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${avenirNext.variable}`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
